[env]                                                                                                                                                                                     
CARGO_INCREMENTAL = 0                                                                                                                                                                     
RUSTFLAGS = "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"                                                          
RUSTDOCFLAGS = "-Cpanic=abort"                                                                                                                                                            
                                                                                                                                                                                          
[tasks.clean]                                                                                                                                                                             
command = "cargo"                                                                                                                                                                         
args = ["+nightly", "clean"]                                                                                                                                                              
                                                                                                                                                                                          
[tasks.test]                                                                                                                                                                              
command = "cargo"                                                                                                                                                                         
args = ["+nightly", "test"]                                                                                                                                                               
dependencies = ["clean"]                                                                                                                                                                  
                                                                                                                                                                                          
[tasks.ccc]                                                                                                                                                                               
command = "grcov"                                                                                                                                                                         
args = [".", "-s", ".", "--binary-path", "./target/debug/", "-t", "html", "--branch", "--ignore-not-existing", "-o", "./target/debug/coverage/"]                                          
dependencies = ["test"]                     
